### ISSUE TITLE
table有问题？

### ISSUE THREAD

**Issue by hellobbq** [SegmentFault/HyperDown#12]
```
| Left-Aligned  | Center Aligned  | Right Aligned |
| :------------ |:---------------:| -----:|
| col 3 is      | some wordy text | $1600 |
| col 2 is      | centered        |   $12 |
| zebra stripes | are neat        |    $1 |

| Item      | Value |
| --------- | -----:|
| Computer  | $1600 |
| Phone     |   $12 |
| Pipe      |    $1 |
```

找的demo，发现错误

| Left-Aligned | Center Aligned | Right Aligned |
| :-- | :-: | --: |
| col 3 is | some wordy text | $1600 |
| col 2 is | centered | $12 |
| zebra stripes | are neat | $1 |

| Item | Value |
| --- | --: |
| Computer | $1600 |
| Phone | $12 |
| Pipe | $1 |

**Comment by joyqi** [comment]
这个bug在后端没有出现，应该是HyperDown.js的前端bug，我将把它移动到相应的repo处理

**Comment by joyqi** [comment]
This issue was moved to SegmentFault/HyperDown.js#7
