### ISSUE TITLE
可以增加composer支持么？

### ISSUE THREAD

**Issue by takashiki** [SegmentFault/HyperDown#14]

**Comment by lvye** [comment]
你好，是支持的https://packagist.org/packages/joyqi/hyper-down

**Comment by takashiki** [comment]
额，好吧，没加dev-master，直接搜hyper-down又在很后面，没看到，要是能在readme里加一下说明就更好了。

**Comment by rabbitLove520** [comment]
是呀，readme里头也添加一下说明呗
