### ISSUE TITLE
如何保留$$ ... $$之间的代码？

### ISSUE THREAD

**Issue by xaero7** [SegmentFault/HyperDown#21]
如何保留$$ ... $$之间的代码，另外也保留`latex ....`之间的代码块，使其不要解析成传统code？

**Comment by dxkite** [comment]
恩，个人不才，修改了下源码，保留了MathJax。。就是不知道你还用不用这个。

![image](https://cloud.githubusercontent.com/assets/7450707/19723173/a4c54d2c-9bac-11e6-8635-951ce38fa01f.png)

代码以及渲染效果

![image](https://cloud.githubusercontent.com/assets/7450707/19723199/b8be0dfa-9bac-11e6-9690-ac5aaf97b0c0.png)
![image](https://cloud.githubusercontent.com/assets/7450707/19723212/c02e433e-9bac-11e6-836f-76930f608c00.png)

反正这种东西求人不如求己。
我上次的pr都没接，这次就不pr了，那天有空自己写个解析器。。

**Comment by joyqi** [comment]
已修复
