### ISSUE TITLE
行内代码解析问题，造成部分内容不显示

### ISSUE THREAD

**Issue by jamesfancy** [SegmentFault/HyperDown#3]
具体情况请看 http://segmentfault.com/q/1010000003098262 上的讨论

虽然不能确定是 HyperDown 造成的，但是我猜是，估计 SegmentFault 最近后台换 HyperDown 解析了。
顺便，希望 HyperDown 的解析能和预览里的脚本解析效果一致，不然预览都不可信了。

**Comment by scarletsky** [comment]
其实我也遇到了，`git-pages`上面和预览上面显示得都是正确的，结果发出去就有大半内容没显示出来。
