### ISSUE TITLE
Could not find package joyqi/hyper-down at any version for your minimum-stability (stable). 

### ISSUE THREAD

**Issue by shiny** [SegmentFault/HyperDown#30]
HyperDown 发布以来经过数年考验，应该可以添加一个正式的版本号了吧？但是 composer 上还停留在 dev-master。
如果不添加，composer 添加时将会导致如上的错误提示，只能指定 `composer require joyqi/hyper-down:dev-master`

**Comment by joyqi** [comment]
已经更新
