### ISSUE TITLE
希望四个 ```` 包裹 markdown 源码时，markdown 源码以代码段形式展示 ，不做转义

### ISSUE THREAD

**Issue by fenbox** [SegmentFault/HyperDown#39]
SF 社区用户反馈，github、stackoverflow 都实现了，比如想实现下面这样的 markdown 代码展示：

````
```
hell world
```
````

**Comment by kecrily** [comment]
@fenbox 刚刚看了一下你的回复内容，发现你使用是的 ```  ，而不是 ```` 。

我又在 GitHub 中尝试了一下该语法，该语法其实是与 ``` 相同的解析方式，也就是该效果原先就可以实现。```` 其实是一种错误的解析。

**Comment by fenbox** [comment]
@scvoet 你应该看下我的源码

![image](https://user-images.githubusercontent.com/360618/71404520-b947c280-266d-11ea-97e4-28c81a5eb3d3.png)

**Comment by kecrily** [comment]
```
> SF 社区用户反馈，github、stackoverflow 都实现了
> 
> ```
> ```
> hell world
> ```
> ```
```
@fenbox 以上是我通过 GitHub 回复功能获取到的源码，这与你截图中的不同。````被转为```，由此也可以判断这是一个错误解析

**Comment by fenbox** [comment]
@scvoet 根据 [GitHub Flavored Markdown](https://github.github.com/gfm/#fenced-code-blocks) 的描述，这并不是错误解析。

> A code fence is a sequence of at least three consecutive backtick characters (`) or tildes (~). (Tildes and backticks cannot be mixed.) A fenced code block begins with a code fence, indented no more than three spaces.
>
> The closing code fence must use the same character as the opening fence

而你引用出现的三个 <code>`</code>，可能是 github 引用功能的 bug。

**Comment by kecrily** [comment]
@fenbox 根据该描述虽然这并不属于错误，但其实两者实际效果相同。故该需求意义不大，用```即可实现展示 Markdown 代码内容了。

**Comment by fenbox** [comment]
@scvoet 那你看下如何用 `` ``` `` 实现我下图这个一模一样的效果（包括里面的文本）

![image](https://user-images.githubusercontent.com/360618/71441480-946e5080-273c-11ea-8053-7ea89602c497.png)

**Comment by kecrily** [comment]
```
    hello,world
    ```

@fenbox 刚刚尝试了一下，发现确实是无法通过```来实现的，是我过于主观臆断了。

但可以采用四个 `space` 来替换 ``` 来实现
