### ISSUE TITLE
非行首元素解析存在问题

### ISSUE THREAD

**Issue by lizheming** [SegmentFault/HyperDown#5]
像 `**粗体**` 这种解析两边必须存在空格，如果写成这样

```
大家好**我是粗体**
```

是不会被解析的。

**Comment by lizheming** [comment]
我看了一下，和 #3 这个 issue 是一样的问题。

**Comment by joyqi** [comment]
已在 f7dea87813f95b9d0b7e2e42ff3bf5d990d668c9 中修复
